import Alligator from "./models/Alligator.js";
import Bear from "./models/Bear.js";
import Camel from "./models/Camel.js";
import Deer from "./models/Deer.js";
import Elephant from "./models/Elephant.js";
import Flamingo from "./models/Flamingo.js";
import Giraffe from "./models/Giraffe.js";
import Hippo from "./models/Hippo.js";
import Iguana from "./models/Iguana.js";
import Jaguar from "./models/Jaguar.js";
import Kangaroo from "./models/Kangaroo.js";
import Lemur from "./models/Lemur.js";
import Meerkat from "./models/Meerkat.js";
import Nyala from "./models/Nyala.js";
import Ostrich from "./models/Ostrich.js";
import Panda from "./models/Panda.js";
import Quokka from "./models/Quokka.js";
import Rhino from "./models/Rhino.js";
import Sloth from "./models/Sloth.js";
import Tiger from "./models/Tiger.js";
import Urial from "./models/Urial.js";
import Vulture from "./models/Vulture.js";
import Walrus from "./models/Walrus.js";
import Xerus from "./models/Xerus.js";
import Yak from "./models/Yak.js";
import Zebra from "./models/Zebra.js";

let ally = new Alligator("Ally", "Green", "F", 200, 60, "big", "Adult", "Florida");
let bobo = new Bear("Bobo", "Grizzly", "Brown", "M", "Standing: 8ft", 684, "Mature", "Montana");
let carly = new Camel("Carly", "Sandy", 2, "F", "5ft", 942, "Adult", "Saudi Arabia");
let darla = new Deer("Darla", "Mule", "Brown", "F", 0, "4ft", 127, "Youth", "Colorado");
let earnie = new Elephant("Earnie", "African Bush", "Grey", 2, true, "M", "11.5ft", 10753, "Mature", "Ethiopia");
let franny = new Flamingo("Franny", "Pink", "F", "4ft", 6, "Adult", "Chile");
let giovani = new Giraffe("Giovani", "Northern Giraffe", "Sandy base with brown spots", "M", "11ft", 1020, "Youth", "Zambia");
let hank = new Hippo("Hank", "Pinkish-Blueish-Grey", "M", "5ft", 4221, "Mature", "Uganda");
let iggy = new Iguana("Iggy", "Blue Iguana", "Turqouise", true, true, "M", "1ft", 27, "5ft", "Adult", "Cayman Islands");
let jade = new Jaguar("Jade", "Black", "F", true, "2ft", "175", "Adult", "Bolivia");
let karl = new Kangaroo("Karl", "Eastern Grey", "Tan/Grey", "M", "5.5ft", 109, "Adult", "Australia");
let larry = new Lemur("Larry", "Ring-tailed", "Grey with black and white tail", true, "M", "1.5ft", 5.5, "Adult", "Madagascar");
let mary = new Meerkat("Mary", "Tan/Sandy", "F", "0.75", 1, "Youth", "South Africa");
let nikko = new Nyala("Nikko", "Dark brown with subtle white stripes", "M", true, "3.5ft", 209, "Adult", "Zimbabwe");
let oscar = new Ostrich("Oscar", "Black", "M", "9ft", 239, "Mature", "Kenya");
let peter = new Panda("Peter", "Giant", "Black and white", "M", "Standing: 5.5ft", 199, "Adult", "China");
let quinn = new Quokka("Quinn", "Reddish-brown", "F", true, "1ft", 5, "Youth", "Australia");
let reggie = new Rhino("Reggie", "Indian Rhino", 1, "Grey", "M", "6ft", 4227, "Adult", "India");
let sammie = new Sloth("Sammie", "Three-toed", "Dark brown and tan", "F", "2ft", 8, "Adult", "Brazil");
let tim = new Tiger("Tim", "Siberian", "Orange and black", "M", true, "3.5ft", 687, "Mature", "Russia");
let unique = new Urial("Unique", "Light brown", "F", true, "3ft", 102, "Adult", "Iran");
let vinny = new Vulture("Vinny", "Turkey", "Black", "M", "3.5ft", 9, "Mature", "Mexico");
let wilma = new Walrus("Wilma", "Pacific", "Sandy", 2, "F", "4ft", 2318, "Mature", "Alaska");
let xavier = new Xerus("Xavier", "Tan", "M", true, "1ft", 1, "Youth", "South Africa");
let yolanda = new Yak("Yolanda", "Brown", "F", true, "5.5ft", 480, "Adult", "China");
let ziggy = new Zebra("Ziggy", "Grevy's", "Black and white", "M", "5ft", 849, "Adult", "Kenya");


